"""Add note summary

Revision ID: 7240d90b1e00
Revises: a3237af0007f
Create Date: 2025-09-13 19:36:05.593140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # auto import sqlmodel for migration operations


# revision identifiers, used by Alembic.
revision: str = '7240d90b1e00'
down_revision: Union[str, Sequence[str], None] = 'a3237af0007f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('note', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('note', 'status')
    op.drop_column('note', 'summary')
    # ### end Alembic commands ###
