"""Add note summary4

Revision ID: 81851a4c34ab
Revises: a40884789302
Create Date: 2025-09-13 20:14:06.909511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # auto import sqlmodel for migration operations


# revision identifiers, used by Alembic.
revision: str = '81851a4c34ab'
down_revision: Union[str, Sequence[str], None] = 'a40884789302'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
