"""modify notes table2

Revision ID: 86ed4a630e31
Revises: f60bec6748af
Create Date: 2025-09-13 00:54:08.230570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # auto import sqlmodel for migration operations


# revision identifiers, used by Alembic.
revision: str = '86ed4a630e31'
down_revision: Union[str, Sequence[str], None] = 'f60bec6748af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
