"""Add note summary3

Revision ID: a40884789302
Revises: 2290db6d7314
Create Date: 2025-09-13 20:11:50.691129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # auto import sqlmodel for migration operations


# revision identifiers, used by Alembic.
revision: str = 'a40884789302'
down_revision: Union[str, Sequence[str], None] = '2290db6d7314'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
