"""Fix Note timestamps defaults

Revision ID: eb53e99841d5
Revises: 86ed4a630e31
Create Date: 2025-09-13 00:56:59.319701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # auto import sqlmodel for migration operations


# revision identifiers, used by Alembic.
revision: str = 'eb53e99841d5'
down_revision: Union[str, Sequence[str], None] = '86ed4a630e31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
