"""init db 3

Revision ID: ff807d7be945
Revises: 1b1df18530db
Create Date: 2025-09-12 19:49:46.637121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # auto import sqlmodel for migration operations


# revision identifiers, used by Alembic.
revision: str = 'ff807d7be945'
down_revision: Union[str, Sequence[str], None] = '1b1df18530db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
